# Generated by Django 6.0.3 on 2026-04-18 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_total_alter_orderitem_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Họ tên')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('vehicle', models.CharField(blank=True, max_length=100, verbose_name='Phương tiện')),
                ('avatar', models.ImageField(blank=True, upload_to='shippers/', verbose_name='Ảnh đại diện')),
                ('status', models.CharField(choices=[('active', 'Đang hoạt động'), ('inactive', 'Tạm nghỉ'), ('busy', 'Đang giao hàng')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('area', models.CharField(blank=True, max_length=200, verbose_name='Khu vực phụ trách')),
                ('joined_at', models.DateField(auto_now_add=True, verbose_name='Ngày vào làm')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Shipper',
                'verbose_name_plural': 'Shippers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.shipper', verbose_name='Shipper phụ trách'),
        ),
    ]
