# Generated by Django 6.0.3 on 2026-04-20 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Ảnh')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='Alt text')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Ảnh sản phẩm',
                'verbose_name_plural': 'Ảnh sản phẩm',
                'ordering': ['order'],
            },
        ),
    ]
