# Generated by Django 6.0.3 on 2026-04-24 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.store', verbose_name='Chi nhánh xử lý'),
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='shop.product', verbose_name='Sản phẩm')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='shop.store', verbose_name='Chi nhánh')),
            ],
            options={
                'verbose_name': 'Tồn kho chi nhánh',
                'verbose_name_plural': 'Tồn kho chi nhánh',
                'unique_together': {('store', 'product')},
            },
        ),
    ]
