# Generated by Django 6.0.3 on 2026-04-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_add_storeproduct_and_order_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
