# Generated by Django 6.0.3 on 2026-04-28 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_label', models.CharField(default='Về chúng tôi', max_length=100, verbose_name='Nhãn Hero')),
                ('hero_title', models.CharField(default='Vẻ đẹp <em>chân thực</em><br>từ thiên nhiên', max_length=200, verbose_name='Tiêu đề Hero')),
                ('hero_text', models.TextField(default='Cosmetic Shop — thương hiệu mỹ phẩm thuần thiên nhiên, chính hãng hàng đầu Việt Nam. Chúng tôi tin rằng mỗi người đều xứng đáng được chăm sóc bằng những sản phẩm an toàn, hiệu quả và bền vững.', verbose_name='Mô tả Hero')),
                ('hero_image', models.ImageField(blank=True, upload_to='about/', verbose_name='Ảnh Hero')),
                ('branches_text', models.CharField(default='Chi nhánh', max_length=50, verbose_name='Text Chi nhánh')),
                ('customers_text', models.CharField(default='Khách hàng', max_length=50, verbose_name='Text Khách hàng')),
                ('products_text', models.CharField(default='Sản phẩm', max_length=50, verbose_name='Text Sản phẩm')),
                ('rating_text', models.CharField(default='Đánh giá', max_length=50, verbose_name='Text Đánh giá')),
                ('story_label', models.CharField(default='Câu chuyện của chúng tôi', max_length=100, verbose_name='Nhãn Story')),
                ('story_title', models.CharField(default='Từ đam mê đến thương hiệu', max_length=200, verbose_name='Tiêu đề Story')),
                ('story_year', models.CharField(default='2019', max_length=10, verbose_name='Năm thành lập')),
                ('story_year_label', models.CharField(default='Năm thành lập', max_length=50, verbose_name='Label Năm')),
                ('story_image', models.ImageField(blank=True, upload_to='about/', verbose_name='Ảnh Story')),
                ('story_text_1', models.TextField(default='Cosmetic Shop được thành lập năm 2019 bởi nhóm những người trẻ đam mê vẻ đẹp tự nhiên và bền vững. Khởi đầu từ một cửa hàng nhỏ tại Quận Tân Bình, TP.HCM, chúng tôi đã nhanh chóng chinh phục khách hàng bằng cam kết về chất lượng và sự tận tâm.', verbose_name='Đoạn văn 1')),
                ('story_text_2', models.TextField(default='Sau 5 năm phát triển, Cosmetic Shop đã mở rộng hệ thống chi nhánh trên toàn thành phố, phục vụ hàng chục nghìn khách hàng mỗi tháng. Mỗi sản phẩm đều được chọn lọc kỹ càng từ các thương hiệu uy tín trong và ngoài nước, đảm bảo an toàn và hiệu quả tuyệt đối.', verbose_name='Đoạn văn 2')),
                ('authentic_text', models.CharField(default='Sản phẩm chính hãng', max_length=50, verbose_name='Text 100%')),
                ('return_text', models.CharField(default='Ngày đổi trả', max_length=50, verbose_name='Text Đổi trả')),
                ('support_text', models.CharField(default='Hỗ trợ khách hàng', max_length=50, verbose_name='Text Hỗ trợ')),
                ('values_label', models.CharField(default='Giá trị cốt lõi', max_length=100, verbose_name='Nhãn Giá trị')),
                ('values_title', models.CharField(default='Những điều chúng tôi tin tưởng', max_length=200, verbose_name='Tiêu đề Giá trị')),
                ('cta_title', models.CharField(default='Sẵn sàng trải nghiệm<br>vẻ đẹp <em>đích thực</em>?', max_length=200, verbose_name='Tiêu đề CTA')),
                ('cta_text', models.TextField(default='Khám phá hàng trăm sản phẩm chính hãng hoặc ghé thăm chi nhánh gần nhất để được tư vấn miễn phí.', verbose_name='Mô tả CTA')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Trang giới thiệu',
                'verbose_name_plural': 'Trang giới thiệu',
            },
        ),
        migrations.CreateModel(
            name='AboutGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/gallery/', verbose_name='Ảnh')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Chú thích')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='shop.aboutpage')),
            ],
            options={
                'verbose_name': 'Ảnh thư viện',
                'verbose_name_plural': 'Ảnh thư viện',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='🌿', max_length=20, verbose_name='Icon')),
                ('title', models.CharField(max_length=100, verbose_name='Tiêu đề')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='shop.aboutpage')),
            ],
            options={
                'verbose_name': 'Giá trị cốt lõi',
                'verbose_name_plural': 'Giá trị cốt lõi',
                'ordering': ['order'],
            },
        ),
    ]
