--
-- PostgreSQL database dump
--

-- Dumped from database version 16.8
-- Dumped by pg_dump version 16.8

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: getallproducts(); Type: PROCEDURE; Schema: public; Owner: postgres
--

CREATE PROCEDURE public.getallproducts()
    LANGUAGE plpgsql
    AS $$
BEGIN
    SELECT * FROM products;
END;
$$;


ALTER PROCEDURE public.getallproducts() OWNER TO postgres;

--
-- Name: getproductbyid(integer); Type: PROCEDURE; Schema: public; Owner: postgres
--

CREATE PROCEDURE public.getproductbyid(IN product_id integer)
    LANGUAGE plpgsql
    AS $$
BEGIN
    SELECT *
    FROM products
    WHERE id = product_id;
END;
$$;


ALTER PROCEDURE public.getproductbyid(IN product_id integer) OWNER TO postgres;

--
-- Name: updatestock(integer, integer); Type: PROCEDURE; Schema: public; Owner: postgres
--

CREATE PROCEDURE public.updatestock(IN product_id integer, IN quantity integer)
    LANGUAGE plpgsql
    AS $$
BEGIN
    UPDATE products
    SET stock = stock - quantity
    WHERE id = product_id;
END;
$$;


ALTER PROCEDURE public.updatestock(IN product_id integer, IN quantity integer) OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: shop_aboutgallery; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shop_aboutgallery (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    caption character varying(200) NOT NULL,
    "order" integer NOT NULL,
    about_id bigint NOT NULL,
    CONSTRAINT shop_aboutgallery_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.shop_aboutgallery OWNER TO postgres;

--
-- Name: shop_aboutgallery_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shop_aboutgallery ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_aboutgallery_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_aboutpage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shop_aboutpage (
    id bigint NOT NULL,
    hero_label character varying(100) NOT NULL,
    hero_title character varying(200) NOT NULL,
    hero_text text NOT NULL,
    hero_image character varying(100) NOT NULL,
    branches_text character varying(50) NOT NULL,
    customers_text character varying(50) NOT NULL,
    products_text character varying(50) NOT NULL,
    rating_text character varying(50) NOT NULL,
    story_label character varying(100) NOT NULL,
    story_title character varying(200) NOT NULL,
    story_year character varying(10) NOT NULL,
    story_year_label character varying(50) NOT NULL,
    story_image character varying(100) NOT NULL,
    story_text_1 text NOT NULL,
    story_text_2 text NOT NULL,
    authentic_text character varying(50) NOT NULL,
    return_text character varying(50) NOT NULL,
    support_text character varying(50) NOT NULL,
    values_label character varying(100) NOT NULL,
    values_title character varying(200) NOT NULL,
    cta_title character varying(200) NOT NULL,
    cta_text text NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.shop_aboutpage OWNER TO postgres;

--
-- Name: shop_aboutpage_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shop_aboutpage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_aboutpage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_aboutvalue; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shop_aboutvalue (
    id bigint NOT NULL,
    icon character varying(20) NOT NULL,
    title character varying(100) NOT NULL,
    description text NOT NULL,
    "order" integer NOT NULL,
    about_id bigint NOT NULL,
    CONSTRAINT shop_aboutvalue_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.shop_aboutvalue OWNER TO postgres;

--
-- Name: shop_aboutvalue_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shop_aboutvalue ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_aboutvalue_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shop_category (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(120) NOT NULL,
    icon character varying(10) NOT NULL,
    description text NOT NULL,
    "order" integer NOT NULL,
    CONSTRAINT shop_category_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.shop_category OWNER TO postgres;

--
-- Name: shop_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shop_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_order; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shop_order (
    id bigint NOT NULL,
    customer_name character varying(200) NOT NULL,
    phone character varying(20) NOT NULL,
    address character varying(300) NOT NULL,
    latitude double precision,
    longitude double precision,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    total numeric(15,0) NOT NULL,
    shipper_id bigint,
    store_id bigint,
    user_id integer
);


ALTER TABLE public.shop_order OWNER TO postgres;

--
-- Name: shop_order_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shop_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_orderitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shop_orderitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    price numeric(15,0) NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL
);


ALTER TABLE public.shop_orderitem OWNER TO postgres;

--
-- Name: shop_orderitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shop_orderitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_orderitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shop_product (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    price numeric(15,0) NOT NULL,
    description text NOT NULL,
    image character varying(100) NOT NULL,
    category_id bigint
);


ALTER TABLE public.shop_product OWNER TO postgres;

--
-- Name: shop_product_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shop_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_productimage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shop_productimage (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    "order" integer NOT NULL,
    alt character varying(200) NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT shop_productimage_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.shop_productimage OWNER TO postgres;

--
-- Name: shop_productimage_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shop_productimage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_productimage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_shipper; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shop_shipper (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    phone character varying(20) NOT NULL,
    email character varying(254) NOT NULL,
    vehicle character varying(100) NOT NULL,
    avatar character varying(100) NOT NULL,
    status character varying(20) NOT NULL,
    area character varying(200) NOT NULL,
    joined_at date NOT NULL,
    note text NOT NULL
);


ALTER TABLE public.shop_shipper OWNER TO postgres;

--
-- Name: shop_shipper_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shop_shipper ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_shipper_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_store; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shop_store (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    address character varying(300) NOT NULL,
    phone character varying(20) NOT NULL,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL
);


ALTER TABLE public.shop_store OWNER TO postgres;

--
-- Name: shop_store_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shop_store ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_store_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_storeproduct; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shop_storeproduct (
    id bigint NOT NULL,
    stock integer NOT NULL,
    product_id bigint NOT NULL,
    store_id bigint NOT NULL,
    CONSTRAINT shop_storeproduct_stock_check CHECK ((stock >= 0))
);


ALTER TABLE public.shop_storeproduct OWNER TO postgres;

--
-- Name: shop_storeproduct_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shop_storeproduct ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_storeproduct_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add store	7	add_store
26	Can change store	7	change_store
27	Can delete store	7	delete_store
28	Can view store	7	view_store
29	Can add order item	8	add_orderitem
30	Can change order item	8	change_orderitem
31	Can delete order item	8	delete_orderitem
32	Can view order item	8	view_orderitem
33	Can add product	9	add_product
34	Can change product	9	change_product
35	Can delete product	9	delete_product
36	Can view product	9	view_product
37	Can add order	10	add_order
38	Can change order	10	change_order
39	Can delete order	10	delete_order
40	Can view order	10	view_order
41	Can add Shipper	11	add_shipper
42	Can change Shipper	11	change_shipper
43	Can delete Shipper	11	delete_shipper
44	Can view Shipper	11	view_shipper
45	Can add Danh mục	12	add_category
46	Can change Danh mục	12	change_category
47	Can delete Danh mục	12	delete_category
48	Can view Danh mục	12	view_category
49	Can add Ảnh sản phẩm	13	add_productimage
50	Can change Ảnh sản phẩm	13	change_productimage
51	Can delete Ảnh sản phẩm	13	delete_productimage
52	Can view Ảnh sản phẩm	13	view_productimage
53	Can add Tồn kho chi nhánh	14	add_storeproduct
54	Can change Tồn kho chi nhánh	14	change_storeproduct
55	Can delete Tồn kho chi nhánh	14	delete_storeproduct
56	Can view Tồn kho chi nhánh	14	view_storeproduct
57	Can add Trang giới thiệu	16	add_aboutpage
58	Can change Trang giới thiệu	16	change_aboutpage
59	Can delete Trang giới thiệu	16	delete_aboutpage
60	Can view Trang giới thiệu	16	view_aboutpage
61	Can add Ảnh thư viện	15	add_aboutgallery
62	Can change Ảnh thư viện	15	change_aboutgallery
63	Can delete Ảnh thư viện	15	delete_aboutgallery
64	Can view Ảnh thư viện	15	view_aboutgallery
65	Can add Giá trị cốt lõi	17	add_aboutvalue
66	Can change Giá trị cốt lõi	17	change_aboutvalue
67	Can delete Giá trị cốt lõi	17	delete_aboutvalue
68	Can view Giá trị cốt lõi	17	view_aboutvalue
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
2	pbkdf2_sha256$1200000$oYrZE3cM1SMTtOF8WHYC0V$rvsmo7lvF+02hAMNosp3U9XdO+wvorAGr5zpIsHt8fQ=	2026-03-29 23:30:39.998845-07	f	Phamhuuan123				f	t	2026-03-06 00:31:20.978936-08
1	pbkdf2_sha256$1200000$Dmk2ViSpp01n3xnNIeTYLK$jdcYxISubfJ1gZMfwQ/0p4nnCyiGUNO0gFuw4OcQ0eo=	2026-05-04 11:12:00.314158-07	t	admin				t	t	2026-01-31 01:17:02.905839-08
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-01-31 01:43:34.959845-08	1	Chanel shop cơ sở Lê Văn Sĩ	1	[{"added": {}}]	7	1
2	2026-03-05 04:17:38.431743-08	1	Nước hoa Chanel	1	[{"added": {}}]	9	1
3	2026-03-05 22:05:34.314159-08	2	Store Chanel VIP 1	1	[{"added": {}}]	7	1
4	2026-03-05 22:06:49.693734-08	2	Store Chanel VIP 1	2	[{"changed": {"fields": ["Longitude"]}}]	7	1
5	2026-03-19 10:59:18.816112-07	26	Serum SK-II Facial Treatment Essence	2	[{"changed": {"fields": ["Image"]}}]	9	1
6	2026-03-19 11:00:11.663403-07	25	Kem Dưỡng Sulwhasoo Concentrated Ginseng Renewing Cream	2	[{"changed": {"fields": ["Image"]}}]	9	1
7	2026-03-19 11:00:15.342594-07	25	Kem Dưỡng Sulwhasoo Concentrated Ginseng Renewing Cream	2	[]	9	1
8	2026-03-19 11:00:53.041744-07	24	Phấn Má Hồng 3CE Mood Recipe Face Blush	2	[{"changed": {"fields": ["Image"]}}]	9	1
9	2026-03-19 11:01:37.558695-07	23	Mascara Maybelline Lash Sensational	2	[{"changed": {"fields": ["Image"]}}]	9	1
10	2026-03-19 11:02:11.537826-07	22	Cushion Laneige Neo Cushion Matte SPF42	2	[{"changed": {"fields": ["Image"]}}]	9	1
11	2026-03-19 11:02:54.310439-07	21	Nước Hoa Hồng Mamonde Rose Water Toner	2	[{"changed": {"fields": ["Image"]}}]	9	1
12	2026-03-19 11:03:24.194049-07	20	Toner Klairs Supple Preparation Unscented	2	[{"changed": {"fields": ["Image"]}}]	9	1
13	2026-03-19 11:04:03.11105-07	19	Mặt Nạ Đất Sét Innisfree Volcanic Pore Clay Mask	2	[{"changed": {"fields": ["Image"]}}]	9	1
14	2026-03-19 11:04:27.322555-07	18	Mặt Nạ Ngủ Laneige Water Sleeping Mask	2	[{"changed": {"fields": ["Image"]}}]	9	1
15	2026-03-19 11:04:59.825779-07	17	Mặt Nạ Giấy Mediheal N.M.F Aquaring Ampoule Mask	2	[{"changed": {"fields": ["Image"]}}]	9	1
16	2026-03-19 11:05:27.973538-07	16	Kem Dưỡng Innisfree Green Tea Seed Cream	2	[{"changed": {"fields": ["Image"]}}]	9	1
17	2026-03-19 11:05:57.707985-07	15	Kem Dưỡng CeraVe Moisturizing Cream	2	[{"changed": {"fields": ["Image"]}}]	9	1
18	2026-03-19 11:06:23.055205-07	14	Kem Dưỡng Ẩm Neutrogena Hydro Boost Water Gel	2	[{"changed": {"fields": ["Image"]}}]	9	1
19	2026-03-19 11:08:33.45472-07	13	Serum Hyaluronic Acid La Roche-Posay	2	[{"changed": {"fields": ["Image"]}}]	9	1
20	2026-03-19 11:08:59.795279-07	12	Serum Niacinamide 10% + Zinc 1% The Ordinary	2	[{"changed": {"fields": ["Image"]}}]	9	1
21	2026-03-19 11:09:22.715982-07	11	Serum Vitamin C The Ordinary Ascorbic Acid 8%	2	[{"changed": {"fields": ["Image"]}}]	9	1
22	2026-03-19 11:09:51.88398-07	10	Kem Chống Nắng Skin1004 Madagascar Centella	2	[{"changed": {"fields": ["Image"]}}]	9	1
23	2026-03-19 11:10:12.800043-07	9	Kem Chống Nắng Bioré UV Aqua Rich Watery Essence	2	[{"changed": {"fields": ["Image"]}}]	9	1
24	2026-03-19 11:11:38.000195-07	8	Kem Chống Nắng Anessa Perfect UV Sunscreen SPF50+	2	[{"changed": {"fields": ["Image"]}}]	9	1
25	2026-03-19 11:11:59.443851-07	7	Sữa Rửa Mặt Simple Kind to Skin	2	[{"changed": {"fields": ["Image"]}}]	9	1
26	2026-03-19 11:14:59.829254-07	6	Gel Rửa Mặt La Roche-Posay Effaclar	2	[{"changed": {"fields": ["Image"]}}]	9	1
27	2026-03-19 11:15:36.531135-07	6	Gel Rửa Mặt La Roche-Posay Effaclar	2	[{"changed": {"fields": ["Image"]}}]	9	1
28	2026-03-19 11:15:47.742153-07	6	Gel Rửa Mặt La Roche-Posay Effaclar	2	[{"changed": {"fields": ["Image"]}}]	9	1
29	2026-03-19 11:22:01.102301-07	5	Sữa Rửa Mặt Cetaphil Gentle Skin Cleanser	2	[{"changed": {"fields": ["Image"]}}]	9	1
30	2026-03-19 11:22:31.410248-07	4	Son Kem Lì 3CE Velvet Lip Tint	2	[{"changed": {"fields": ["Image"]}}]	9	1
31	2026-03-19 11:23:02.848175-07	3	Son Dưỡng Môi L'Oreal Color Riche	2	[{"changed": {"fields": ["Image"]}}]	9	1
32	2026-03-19 11:23:53.685224-07	2	Son Lì Maybelline SuperStay Matte Ink	2	[{"changed": {"fields": ["Image"]}}]	9	1
33	2026-03-30 02:47:38.995976-07	2	Order #2 - admin	3		10	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	shop	store
8	shop	orderitem
9	shop	product
10	shop	order
11	shop	shipper
12	shop	category
13	shop	productimage
14	shop	storeproduct
15	shop	aboutgallery
16	shop	aboutpage
17	shop	aboutvalue
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-01-31 01:16:01.119236-08
2	auth	0001_initial	2026-01-31 01:16:01.186425-08
3	admin	0001_initial	2026-01-31 01:16:01.203703-08
4	admin	0002_logentry_remove_auto_add	2026-01-31 01:16:01.219663-08
5	admin	0003_logentry_add_action_flag_choices	2026-01-31 01:16:01.225119-08
6	contenttypes	0002_remove_content_type_name	2026-01-31 01:16:01.235336-08
7	auth	0002_alter_permission_name_max_length	2026-01-31 01:16:01.239921-08
8	auth	0003_alter_user_email_max_length	2026-01-31 01:16:01.245211-08
9	auth	0004_alter_user_username_opts	2026-01-31 01:16:01.249166-08
10	auth	0005_alter_user_last_login_null	2026-01-31 01:16:01.254411-08
11	auth	0006_require_contenttypes_0002	2026-01-31 01:16:01.254411-08
12	auth	0007_alter_validators_add_error_messages	2026-01-31 01:16:01.260397-08
13	auth	0008_alter_user_username_max_length	2026-01-31 01:16:01.270221-08
14	auth	0009_alter_user_last_name_max_length	2026-01-31 01:16:01.275161-08
15	auth	0010_alter_group_name_max_length	2026-01-31 01:16:01.279873-08
16	auth	0011_update_proxy_permissions	2026-01-31 01:16:01.283862-08
17	auth	0012_alter_user_first_name_max_length	2026-01-31 01:16:01.288303-08
18	sessions	0001_initial	2026-01-31 01:16:01.298802-08
19	shop	0001_initial	2026-01-31 01:43:11.386071-08
20	shop	0002_alter_order_total_alter_orderitem_price_and_more	2026-04-05 09:42:18.695948-07
21	shop	0003_shipper_order_shipper	2026-04-18 09:46:46.669638-07
22	shop	0004_category_product_category	2026-04-19 03:15:19.467694-07
23	shop	0005_productimage	2026-04-20 00:02:43.677217-07
24	shop	0006_add_storeproduct_and_order_store	2026-04-24 09:55:46.149607-07
25	shop	0007_remove_product_stock	2026-04-24 10:07:04.919684-07
26	shop	0008_aboutpage_aboutgallery_aboutvalue	2026-04-28 04:25:04.119365-07
27	shop	0009_order_user_alter_order_status	2026-04-28 10:21:11.933033-07
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
tfszsf2nndi2290l63xlqq8kp91bsfx3	.eJxVjDkOwjAQAP_iGllZr-ODkj5viDbeNQ4gW8pRIf6OIqWAdmY0bzXSvpVxX2UZZ1ZXBeryyyZKT6mH4AfVe9Op1W2ZJ30k-rSrHhrL63a2f4NCazm2ziB6K8lnMACEAWN00UBvnUw9CyfsgDtPOWREJm8zZmT2mCgFUJ8vvMA3nQ:1vm7BB:sHdcPb0mZ-9m-26u8GIUaEIY_HYKXnD52UpLASmCReg	2026-02-14 01:22:09.617669-08
pbxxpcielhyz1ctqqpnzgww79gvngyhh	.eJxVjDsOwjAQBe_iGln-fyjpOYO1u7ZxADlSnFSIu0OkFNC-mXkvlmBbW9pGWdKU2ZlJdvrdEOhR-g7yHfpt5jT3dZmQ7wo_6ODXOZfn5XD_DhqM9q3JVTRSa-d1FblizqQERAdIoUJBsA6DltFIo7xVIQQtKrkYhSkWlWfvD_p6N9U:1w796A:rBb3Jml6aBFlQZt-cknU-ihg0YF6MI7JTWGN5LTi7bc	2026-04-13 02:39:54.712555-07
kxdbk97kvteeydfmwzzmc8p9ldeud2aq	.eJxVjDsOwjAQBe_iGln-fyjpOYO1u7ZxADlSnFSIu0OkFNC-mXkvlmBbW9pGWdKU2ZlJdvrdEOhR-g7yHfpt5jT3dZmQ7wo_6ODXOZfn5XD_DhqM9q3JVTRSa-d1FblizqQERAdIoUJBsA6DltFIo7xVIQQtKrkYhSkWlWfvD_p6N9U:1wJxlw:Z__bGlB3WGtiH50tEDj2okCBNU-kMD7ebpFKSolK3_E	2026-05-18 11:12:00.320159-07
\.


--
-- Data for Name: shop_aboutgallery; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.shop_aboutgallery (id, image, caption, "order", about_id) FROM stdin;
\.


--
-- Data for Name: shop_aboutpage; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.shop_aboutpage (id, hero_label, hero_title, hero_text, hero_image, branches_text, customers_text, products_text, rating_text, story_label, story_title, story_year, story_year_label, story_image, story_text_1, story_text_2, authentic_text, return_text, support_text, values_label, values_title, cta_title, cta_text, updated_at) FROM stdin;
1	Về chúng tôi	Vẻ đẹp <em>chân thực</em><br>từ thiên nhiên	Cosmetic Shop — thương hiệu mỹ phẩm thuần thiên nhiên, chính hãng hàng đầu Việt Nam. Chúng tôi tin rằng mỗi người đều xứng đáng được chăm sóc bằng những sản phẩm an toàn, hiệu quả và bền vững.	about/5bba142e-30f0-4844-8006-920210412e13_8c8ff1b6867c45419040bf0a7b07d337_grande_CaHU5IF.png	Chi nhánh	Khách hàng	Sản phẩm	Đánh giá	Câu chuyện của chúng tôi	Từ đam mê đến thương hiệu	2019	Năm thành lập	about/logo.png	Cosmetic Shop được thành lập năm 2019 bởi nhóm những người trẻ đam mê vẻ đẹp tự nhiên và bền vững. Khởi đầu từ một cửa hàng nhỏ tại Quận Tân Bình, TP.HCM, chúng tôi đã nhanh chóng chinh phục khách hàng bằng cam kết về chất lượng và sự tận tâm.	Sau 5 năm phát triển, Cosmetic Shop đã mở rộng hệ thống chi nhánh trên toàn thành phố, phục vụ hàng chục nghìn khách hàng mỗi tháng. Mỗi sản phẩm đều được chọn lọc kỹ càng từ các thương hiệu uy tín trong và ngoài nước, đảm bảo an toàn và hiệu quả tuyệt đối.	Sản phẩm chính hãng	Ngày đổi trả	Hỗ trợ khách hàng	Giá trị cốt lõi	Những điều chúng tôi tin tưởng	Sẵn sàng trải nghiệm<br>vẻ đẹp <em>đích thực</em>?	Khám phá hàng trăm sản phẩm chính hãng hoặc ghé thăm chi nhánh gần nhất để được tư vấn miễn phí.	2026-04-28 08:37:13.199481-07
\.


--
-- Data for Name: shop_aboutvalue; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.shop_aboutvalue (id, icon, title, description, "order", about_id) FROM stdin;
\.


--
-- Data for Name: shop_category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.shop_category (id, name, slug, icon, description, "order") FROM stdin;
1	Son môi	son-moi	💄		0
2	Kem dưỡng	kem-duong	🧴		1
3	Nước hoa	nuoc-hoa	🌸		2
4	Chăm sóc mắt	cham-soc-mat	👁️		3
5	Nail & Móng	nail-mong	💅		4
6	Chống nắng	chong-nang	☀️		5
7	Làm sạch	lam-sach	🧼		6
8	Chăm sóc tóc	cham-soc-toc	💆		7
9	Chăm sóc da	cham-soc-da	✨		0
\.


--
-- Data for Name: shop_order; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.shop_order (id, customer_name, phone, address, latitude, longitude, status, created_at, total, shipper_id, store_id, user_id) FROM stdin;
11	admin	0924724824	Hẻm 215 Nguyễn Xí, Khu phố 35, Phường Bình Lợi Trung, Thành phố Thủ Đức, Thành phố Hồ Chí Minh, 72309, Việt Nam	10.817357482109188	106.70372060444217	delivered	2026-04-28 03:50:16.47695-07	2850000	3	1	\N
12	admin	0924724824	Hẻm 215 Nguyễn Xí, Khu phố 35, Phường Bình Lợi Trung, Thành phố Thủ Đức, Thành phố Hồ Chí Minh, 72309, Việt Nam	10.817367598491272	106.70370899638523	delivered	2026-04-28 10:23:31.362755-07	2000000	1	4	1
13	admin	0924724824	Hẻm 215 Nguyễn Xí, Khu phố 35, Phường Bình Lợi Trung, Thành phố Thủ Đức, Thành phố Hồ Chí Minh, 72309, Việt Nam	10.817415726827539	106.70375880699082	pending	2026-05-05 04:45:02.55974-07	4000000	\N	1	1
\.


--
-- Data for Name: shop_orderitem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.shop_orderitem (id, quantity, price, order_id, product_id) FROM stdin;
14	1	2850000	11	25
15	10	200000	12	28
16	20	200000	13	28
\.


--
-- Data for Name: shop_product; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.shop_product (id, name, price, description, image, category_id) FROM stdin;
10	Kem Chống Nắng Skin1004 Madagascar Centella	285000	Kem chống nắng Hàn Quốc chiết xuất rau má, không gây bết dính, phù hợp da dầu mụn.	products/634_cce7ac3a340e47f5986eab4bbd6afb09_1024x1024.jpg	\N
19	Mặt Nạ Đất Sét Innisfree Volcanic Pore Clay Mask	245000	Innisfree Volcanic Pore Clay Mask là mặt nạ đất sét best-seller toàn cầu đến từ Innisfree — thương hiệu mỹ phẩm theo chủ nghĩa tự nhiên đầu tiên tại Hàn Quốc, sử dụng nguyên liệu tự nhiên từ đảo Jeju — nơi có không khí trong lành, đất đai màu mỡ và nguồn nước sạch không bị ô nhiễm. Beautyfriend\r\nLinh hồn của sản phẩm là tro núi lửa Jeju — nguyên liệu quý hiếm được hình thành từ dung nham sau khi núi lửa phun trào, có khả năng hấp thụ bã nhờn và loại bỏ bụi bẩn mạnh mẽ. Beautyfriend Kết hợp cùng Bentonite và Kaolin — hai loại đất sét khoáng có khả năng làm sạch lỗ chân lông sâu tận gốc — tạo nên công thức làm sạch vượt trội mà không gây khô căng da.\r\nThành phần nổi bật: Polyvinyl Alcohol kháng khuẩn và kiểm soát bã nhờn. Bột óc chó tẩy tế bào chết nhẹ nhàng. AHA tăng khả năng sản sinh collagen, chống lão hóa và giúp da chắc khỏe. Hasaki Trehalose và Glycerin dưỡng ẩm, ngăn da bị khô sau khi dùng mặt nạ.\r\n10 công dụng trong 1 sản phẩm: se nhỏ lỗ chân lông, kiểm soát dầu nhờn, tẩy da chết, làm sạch bụi bẩn, tiêu diệt mụn đầu đen, làm sạch sâu, hiệu ứng mát lạnh dễ chịu, làm mềm mịn da, dưỡng sáng và chống lão hóa. Cherry Blossom World Sau khoảng 5 phút đắp, bề mặt da se lại nhẹ nhàng mà không gây căng đau khi cử động mặt. Ngoc Reviews\r\nCam kết không chứa dầu khoáng, paraben và các thành phần từ động vật. Hasaki Phù hợp cho da dầu, da hỗn hợp, da có lỗ chân lông to và da dễ nổi mụn đầu đen. Da khô nên dùng tần suất thấp hơn và dưỡng ẩm kỹ sau mỗi lần dùng.\r\nCách dùng: Làm sạch da kỹ trước khi đắp (có thể xông hơi nhẹ để mở lỗ chân lông). Dùng thìa lấy lượng vừa đủ thoa đều lên mặt, tránh vùng mắt và môi. Để 10–15 phút cho đến khi mặt nạ se lại. Rửa sạch với nước ấm và dưỡng ẩm ngay sau đó. Dùng 1–2 lần mỗi tuần để đạt hiệu quả tối ưu.	products/mat-na-innisfree-super-volcanic-pore-clay-mask-100ml-7.jpg	9
7	Sữa Rửa Mặt Simple Kind to Skin	145000	Sữa rửa mặt không hương liệu, không cồn, dành cho da nhạy cảm. Làm sạch nhẹ nhàng.	products/untitled_75e466c6a9d14bd988c410a08cd4d476.png	7
14	Kem Dưỡng Ẩm Neutrogena Hydro Boost Water Gel	325000	Gel dưỡng ẩm dạng nước, thấm nhanh, không gây bết dính. Cấp ẩm 48h.	products/dd_gel_b2879746c8d84a22856364fe9f6cbf1a_1024x1024_d012fe69b2ef4492b80518b6023b2_R6YMziC.jpg	2
17	Mặt Nạ Giấy Mediheal N.M.F Aquaring Ampoule Mask	35000	Mặt nạ cấp ẩm chuyên sâu, phục hồi da khô, dưỡng da mềm mại.	products/ugiahg.jpg	9
13	Serum Hyaluronic Acid La Roche-Posay	485000	Serum cấp ẩm sâu với Hyaluronic Acid, giúp da căng mọng, tươi trẻ.	products/3337875683739-4_Glycolic-B5_50ml.webp	9
12	Serum Niacinamide 10% + Zinc 1% The Ordinary	295000	Serum kiểm soát dầu, se khít lỗ chân lông, cải thiện vết thâm mụn.	products/the-ordinary-niacinamide-10-zinc-1-30ml.jpg	7
11	Serum Vitamin C The Ordinary Ascorbic Acid 8%	320000	Serum Vitamin C giúp làm sáng da, mờ thâm nám. Chống oxy hóa hiệu quả.	products/the-ordinary-ascorbic-acid-8-alpha-arbutin-2.jpg	7
9	Kem Chống Nắng Bioré UV Aqua Rich Watery Essence	195000	Kem chống nắng dạng gel, thấm nhanh, không nhờn rít. SPF50+ PA++++.	products/77ef3aae-de46-49ac-8502-7d33f8b6c483.webp	6
8	Kem Chống Nắng Anessa Perfect UV Sunscreen SPF50+	550000	Kem chống nắng Nhật Bản cao cấp, chống nước, mồ hôi. Bảo vệ da tối ưu dưới ánh nắng.	products/335-h6-1.png	6
6	Gel Rửa Mặt La Roche-Posay Effaclar	285000	Gel rửa mặt cho da dầu mụn, kiểm soát dầu hiệu quả, làm sạch sâu lỗ chân lông.	products/la-roche-posay-productpage-acne-effaclar-cleansing-foaming-gel-1.webp	7
5	Sữa Rửa Mặt Cetaphil Gentle Skin Cleanser	165000	Sữa rửa mặt dịu nhẹ dành cho da nhạy cảm. pH cân bằng, không gây khô da, phù hợp mọi loại da.	products/00500424_cetaphil_gentle_cleanse_209a0fb517a745dbb2d32b15173aba39_1024x1024.jpg	7
4	Son Kem Lì 3CE Velvet Lip Tint	320000	Son kem Hàn Quốc cao cấp, màu chuẩn, lâu trôi, không gây khô môi. Thiết kế sang trọng.	products/Son-3CE-Velvet-Lip-Tint-Know-Better-3.png	1
3	Son Dưỡng Môi L'Oreal Color Riche	185000	Son dưỡng màu cao cấp, chứa tinh dầu Argan giúp môi mềm mại, ẩm mượt suốt ngày dài.	products/son-duong-loreal-colour-riche-i-pink-you-cute-chinh-hang-made-in-usa-giahuynhphat.com_.jpg	1
2	Son Lì Maybelline SuperStay Matte Ink	219000	Son lì lâu trôi đến 16 giờ, màu sắc rực rỡ, không gây khô môi. Chất son mịn màng, dễ tán đều.	products/69f7342c-9cea-45ab-a107-c7d616c34ba8.webp	1
1	Nước hoa Chanel	15000000	Nước hoa cao cúp	products/nuoc-hoa-chanel-chance-eau-tendre-eau-de-parfum-100ml-e1668826181428.png	3
22	Cushion Laneige Neo Cushion Matte SPF42	625000	Laneige Neo Cushion Matte SPF42 PA++ là phấn nước thuộc thương hiệu Laneige — thương hiệu K-Beauty nổi tiếng toàn cầu trực thuộc tập đoàn AmorePacific, Hàn Quốc. Với tên gọi bắt nguồn từ tiếng Pháp có nghĩa là "tuyết", Laneige luôn hướng tới mang lại làn da trong trẻo, trắng mịn không tì vết cho phái đẹp.\r\nBông mút có thiết kế đặc biệt với các lỗ nhỏ trên bề mặt giúp kem nền phân tán đều hơn, tăng 10% độ che phủ trên da cho lớp nền mịn lì tuyệt đối. Abbeautyworld Thành phần Titanium Dioxide, Zinc Oxide cùng công nghệ độc quyền của Laneige cho khả năng che phủ đáng kinh ngạc — ngay cả các khuyết điểm cứng đầu như thâm mụn, lỗ chân lông to, quầng thâm, nám, tàn nhang cũng được che đậy khéo léo với lớp finish lì mịn, lâu trôi. VILIP\r\nCông dụng nổi bật: Che phủ khuyết điểm mức trung bình cao, che tốt thâm mụn, lỗ chân lông, quầng thâm. Nâng tone và làm đều màu da tự nhiên. Bảo vệ da hoàn hảo trước tác động của tia UV cũng như ánh sáng xanh từ màn hình điện tử nhờ chỉ số SPF42 PA++. Riokupon Kiềm dầu hiệu quả suốt 24 giờ. Bổ sung thành phần dưỡng ẩm giúp da duy trì trạng thái mềm mịn, dễ chịu suốt cả ngày.\r\nBảng màu đa dạng chia theo undertone từ số 13 đến 25 — từ tông sáng đến tối dần, dễ dàng tìm được màu phù hợp với mọi tone da Á Đông. Đặc biệt phù hợp cho da dầu, da hỗn hợp và da hay tiếp xúc với màn hình điện tử.\r\nLưu ý: Sản phẩm có chứa hương liệu, không khuyến khích cho da nhạy cảm dễ dị ứng. Nên dưỡng ẩm kỹ trước khi dùng để tránh tình trạng khô mốc khi ở trong phòng máy lạnh lâu.\r\nCách dùng: Làm sạch da và dưỡng ẩm. Dùng bông mút lấy lượng vừa đủ, tán mỏng đều khắp mặt và cổ. Dùng đầu nhọn của mút để tán vào cánh mũi và khóe mắt cho lớp nền hoàn hảo.	products/1_28055c8179a941ee8931f0faafad12a2.png	9
24	Phấn Má Hồng 3CE Mood Recipe Face Blush	385000	3CE Mood Recipe Face Blush là phấn má hồng đến từ thương hiệu mỹ phẩm Hàn Quốc 3CE (3 Concept Eyes) — thương hiệu makeup được giới trẻ châu Á yêu thích nhờ thiết kế thời thượng và chất lượng vượt trội.\r\nThiết kế hộp phấn hình tròn với phần nắp trong suốt giúp quan sát màu sắc sản phẩm dễ dàng, cùng tông màu pastel nhẹ nhàng, tươi tắn. Annguy Kết cấu phấn nén dạng lì, không nhũ, các hạt phấn mịn bám dính vào da mà không vón cục, tạo nên đôi má ửng hồng tự nhiên, mang lại màu sắc vui tươi và quyến rũ. Lamthaocosmetics\r\nCông dụng nổi bật: Tạo đôi gò má ửng hồng tự nhiên, rạng rỡ. Chất phấn giàu sắc tố lên rõ màu, độ bám tốt, để lớp phấn má trên da luôn thoáng mịn cả ngày, hạn chế tình trạng cakey. Kiểm soát dầu giúp bề mặt da khô ráo, thoáng nhẹ. SonAuth Bám màu từ 5 đến 8 tiếng, không lo lớp phấn bị mờ hay trôi. Phù hợp mọi loại da, kể cả da dầu và da nhạy cảm.\r\nBảng màu đa dạng theo xu hướng: Nude Peach (cam đào), Mono Pink (hồng baby), City Mauve (hồng pastel), Rose Beige (cam hồng đất), Peach Splash (cam nude), Fools In Love (hồng sữa dâu), Delectable (hồng phấn) và nhiều màu khác — dễ phối hợp với nhiều phong cách trang điểm từ tự nhiên đến cá tính.\r\nCách dùng: Dùng cọ lấy phấn, giũ nhẹ cho rơi bớt phấn dư. Mỉm cười để xác định gò má. Tán phấn theo chuyển động xoay tròn từ gò má ra đến mang tai. Có thể tán nhẹ lên sống mũi và khóe mắt để tạo hiệu ứng sun-kissed tự nhiên.	products/phan_ma_hong_3ce_mood_recipe_face_blush_mono_pink_bad1919224f446b89419e800ae324_q44XEgZ.png	9
23	Mascara Maybelline Lash Sensational	189000	Maybelline Lash Sensational là dòng mascara best-seller toàn cầu của thương hiệu Maybelline New York — Mỹ, được hàng triệu tín đồ makeup yêu thích nhờ hiệu quả ấn tượng và mức giá bình dân. Sản phẩm là lựa chọn lý tưởng cho những ai muốn có đôi mắt to tròn, mi dày cong quyến rũ chỉ trong vài giây.\r\nĐiểm tạo nên sự khác biệt của Lash Sensational chính là cọ quạt độc quyền với mười lớp lông cọ, giúp xòe tròn từng lớp mi để tạo hiệu ứng mi đầy đặn hoàn hảo. Maybelline Công thức được bổ sung dầu Rose Hip dưỡng ẩm giúp mi mềm mượt hơn, không bị gãy rụng. Maybelline\r\nCông dụng nổi bật: Làm dài và dày mi tức thì, tơi rõ từng sợi mi từ chân đến ngọn. Tạo hiệu ứng mi xòe tròn tự nhiên, đôi mắt to tròn và cuốn hút. Không vón cục, không làm nặng mi. Bám màu lâu trôi, giữ form mi cong cả ngày. Phiên bản Waterproof chống nước, chống mồ hôi, không lo lem khi trời mưa hay ngày nóng. Đã được kiểm nghiệm bởi chuyên gia nhãn khoa, an toàn cho người đeo kính áp tròng và mắt nhạy cảm. Maybelline\r\nCó 2 phiên bản: Washable (dễ tẩy trang) và Waterproof (chống nước). Màu sắc: đen huyền, đen tuyền Midnight Black và các tông màu thời trang khác.\r\nCách dùng: Dùng mặt cong bên trong cọ để tiếp cận chân mi. Chuốt từ chân lên ngọn mi theo chuyển động zic-zac. Có thể thoa nhiều lớp để tăng độ dày theo ý muốn — từ tự nhiên đến ấn tượng. Tẩy trang bằng dầu tẩy trang hoặc nước tẩy trang chuyên dụng.	products/lash-sensational-sky-high-mascara_1.webp	4
21	Nước Hoa Hồng Mamonde Rose Water Toner	265000	Mamonde Rose Water Toner là nước cân bằng da nổi tiếng đến từ thương hiệu Mamonde — thương hiệu K-Beauty trực thuộc tập đoàn AmorePacific, thành lập năm 1991. Tên "Ma Monde" trong tiếng Pháp có nghĩa là "Thế giới của tôi" — thương hiệu gắn liền với triết lý ứng dụng tinh hoa hoa cỏ thiên nhiên vào làm đẹp. BlogAnChoi\r\nĐiểm tạo nên sự đặc biệt của sản phẩm chính là công thức với tới 90,97% nước hoa hồng Damask được chưng cất tỉ mỉ, công phu — vừa làm dịu vừa nuôi dưỡng tế bào biểu bì từ sâu bên trong, đồng thời tạo lớp màng giữ ẩm giúp điều tiết dầu thừa và bảo vệ da khỏi tác động môi trường. Laskin\r\nCác thành phần nổi bật: Damask Rose Extract (90,97%) cấp ẩm và làm dịu da. Allantoin tái tạo tế bào da, hỗ trợ phục hồi tổn thương. Cocolux Chiết xuất quả mận chống oxy hóa, thải độc, kháng khuẩn kháng viêm. Chiết xuất hoa sen hỗ trợ chống lão hóa và tẩy da chết nhẹ nhàng. Tromethamine cân bằng pH da và điều tiết bã nhờn. Glycerin và Butylene Glycol cung cấp độ ẩm, làm mềm da. Blogtietkiem\r\nCông dụng nổi bật: Cấp ẩm sâu, duy trì da mềm mại và căng mướt suốt cả ngày. Làm sạch bã nhờn sâu bên trong, thông thoáng lỗ chân lông, giảm nguy cơ hình thành mụn. ChanhTuoi Cân bằng độ pH sau bước rửa mặt. Làm dịu da đỏ, da kích ứng. Giúp các bước dưỡng tiếp theo thẩm thấu hiệu quả hơn. Không chứa cồn, không chất tạo màu, không chất phụ gia — an toàn và lành tính cho mọi loại da. Websosanh\r\nKết cấu dạng nước lỏng trong suốt, thẩm thấu nhanh, mùi hoa hồng dịu nhẹ tự nhiên, mang lại cảm giác mát lạnh và thư giãn khi sử dụng. Phù hợp mọi loại da, đặc biệt lý tưởng cho da khô, da thiếu ẩm và da cần phục hồi sau khi tiếp xúc nhiều với ánh nắng.\r\nCách dùng: Sau bước rửa mặt, lấy lượng vừa đủ ra lòng bàn tay hoặc thấm vào bông cotton, vỗ nhẹ đều khắp mặt và cổ. Dùng sáng và tối mỗi ngày để đạt hiệu quả tốt nhất.	products/nuoc-hoa-hong-mamonde-rose-water-toner_47654a5835374ec28dd2479e69899864_master.jpg	9
15	Kem Dưỡng CeraVe Moisturizing Cream	385000	CeraVe Moisturizing Cream là kem dưỡng ẩm kinh điển đến từ CeraVe — thương hiệu dược mỹ phẩm nổi tiếng của Mỹ, được thành lập năm 2005 bởi 3 nhà khoa học da liễu, là thương hiệu đầu tiên trên thế giới bổ sung thành phần Ceramide và Cholesterol vào sản phẩm chăm sóc da. Thanh Nien Sản phẩm được các bác sĩ da liễu khắp thế giới tin tưởng khuyên dùng cho bệnh nhân.\r\nĐiểm tạo nên sự khác biệt của CeraVe chính là công nghệ MVE (Multivesicular Emulsion) độc quyền — cho phép sản phẩm giải phóng các dưỡng chất theo từng lớp để duy trì độ ẩm ổn định trong suốt 24 giờ. Shopee\r\nThành phần nổi bật: 3 loại Ceramide thiết yếu (Ceramide 1, 3, 6-II) giúp khôi phục và củng cố lớp màng bảo vệ da. Hyaluronic Acid và Glycerin cấp nước, giữ ẩm cho da luôn căng mọng. Dimethicone dưỡng ẩm và làm mịn da. Thanh Nien Ceramides và Cholesterol giúp sửa chữa các tổn thương trên da, ngăn ngừa mất nước và tăng khả năng ngậm nước. Cocolux\r\nCông dụng nổi bật: Dưỡng ẩm sâu, duy trì độ ẩm liên tục suốt 24 giờ. Phục hồi và củng cố hàng rào bảo vệ da bị tổn thương. Phục hồi và chữa lành tổn thương, giảm ngứa ngáy do các bệnh lý như eczema và viêm da cơ địa. Thanh Nien Cải thiện các vùng da khô, sần sùi, mang lại làn da mềm mịn và đều màu hơn. Nhà Thuốc FPT Long Châu Giảm hiện tượng mẩn đỏ, sưng tấy và kích ứng. Dùng được cho cả mặt và toàn thân.\r\nKhông chứa hương liệu, không gây bít tắc lỗ chân lông — phù hợp cho da khô nhạy cảm, da dễ kích ứng và an toàn cho cả mặt và body. Nhà Thuốc FPT Long Châu Kết cấu kem mềm mịn như nhung, thấm nhanh, không gây nhờn rít. Phù hợp da thường đến da khô, đặc biệt lý tưởng cho da bị eczema, viêm da cơ địa và da đang trong quá trình điều trị tích cực với Retinol, BHA, AHA.\r\nCách dùng: Dùng bước cuối trong chu trình dưỡng da sáng và tối sau khi rửa mặt. Lấy lượng vừa đủ thoa đều lên da mặt và cổ, vỗ nhẹ cho dưỡng chất thấm. Có thể dùng cho toàn thân sau khi tắm khi da còn ẩm để khóa ẩm hiệu quả hơn.	products/454g_99d69b6b22114c3d86b4b05238d2b6c6_1024x1024.jpg	2
18	Mặt Nạ Ngủ Laneige Water Sleeping Mask	485000	Laneige Water Sleeping Mask là mặt nạ ngủ best-seller toàn cầu của Laneige — thương hiệu K-Beauty trực thuộc tập đoàn AmorePacific, ra đời năm 1994 với thông điệp "Everyday New Face — mỗi ngày một diện mạo mới". Bachhoaxanh Đây là sản phẩm được hàng triệu phụ nữ châu Á tin dùng như bước skincare cuối ngày không thể thiếu.\r\nBí quyết tạo nên hiệu quả vượt trội chính là công nghệ độc quyền Sleep-tox™ — liệu pháp làm đẹp dành riêng cho làn da thiếu ngủ. Laneige Vietnam Cơ chế hoạt động: sau khi apply lên da, dưỡng chất thấm vào và hình thành lớp màng Beta-Glucan giàu ẩm, khóa ẩm như một lớp phim bảo vệ, đồng thời ổn định các thành phần hiệu quả trong Sleep-tox™ để chúng thấm sâu vào da suốt 8 tiếng ngủ. Beautygarden\r\nThành phần nổi bật: Chiết xuất quả mơ thúc đẩy và tăng cường khả năng giải độc, hỗ trợ làm sạch da tối ưu. Chiết xuất rễ cây anh thảo đào thải chất bẩn tích tụ trên da suốt cả ngày. Beautygarden Glycerin, Trehalose và Squalane cấp ẩm sâu và giữ nước suốt đêm. Beta-Glucan và Tryptophan tái tạo và phục hồi da sau một ngày căng thẳng. Cocolux Hương thơm tự nhiên từ hoa cam, hoa hồng, hoàng lan và dầu đàn hương giúp thư giãn tinh thần, cải thiện chất lượng giấc ngủ. Beautygarden\r\nCông dụng nổi bật: Cấp ẩm sâu, duy trì làn da mềm mịn và căng mọng đến tận sáng hôm sau. Khóa ẩm và lưu giữ dưỡng chất, thúc đẩy đào thải cặn bã, làm sạch sâu từ bên trong, phục hồi và tái tạo da. Myphamphutho Sau 7 ngày sử dụng, độ ẩm trên da được cải thiện tới 9,6% với người ngủ đủ giấc và lên tới 15,79% với người thường xuyên ngủ không ngon. Beautygarden\r\nKết cấu gel trong mịn, mỏng nhẹ, thấm nhanh, không gây bít tắc lỗ chân lông. Mùi hương dịu nhẹ, thư giãn. Phù hợp mọi loại da kể cả da nhạy cảm. Có 2 size: 70ml (dùng lâu dài, tặng kèm muỗng lấy kem) và 15ml (tiện lợi khi du lịch).\r\nCách dùng: Dùng bước cuối trong chu trình dưỡng da buổi tối, sau serum và kem dưỡng. Lấy lượng vừa đủ thoa đều lên mặt và cổ, massage nhẹ nhàng cho thấm. Để qua đêm rồi rửa sạch vào sáng hôm sau. Da dầu dùng 2–3 lần/tuần, da khô có thể dùng hằng đêm. Bảo quản trong tủ lạnh để tăng hiệu quả dưỡng ẩm và cảm giác mát dịu khi sử dụng.	products/mat-na-ngu-duong-am-laneige-water-sleeping-mask-ex-chiaki-vn-png-1640147878-221_hBFvw97.png	9
16	Kem Dưỡng Innisfree Green Tea Seed Cream	295000	Innisfree Green Tea Seed Cream là kem dưỡng ẩm best-seller lâu năm của Innisfree — thương hiệu mỹ phẩm thiên nhiên đầu tiên tại Hàn Quốc, nổi tiếng với triết lý khai thác tinh hoa từ đảo Jeju trong lành. Sản phẩm là bước hoàn thiện lý tưởng trong chu trình skincare hằng ngày, được hàng triệu tín đồ làm đẹp châu Á tin dùng.\r\nLinh hồn của sản phẩm là tinh chất trà xanh Jeju — thành phần chính có công dụng chống oxy hóa thần kỳ, kháng viêm, kháng khuẩn và lành tính cho da mụn, da nhạy cảm. Beautygarden Thành phần dưỡng ẩm chuyên biệt chứa 16 loại amino acid khác nhau, đậm đặc gấp 3,5 lần so với trà xanh thông thường. Innisfree\r\nThành phần nổi bật: Cyclopentasiloxane — hợp chất silicon giúp dưỡng ẩm, làm mềm da và hạn chế tối đa tình trạng mất độ ẩm ra ngoài. Beautygarden Tocopherol (Vitamin E) chống oxy hóa, bảo vệ da khỏi tia UV và tăng cường tái tạo da. Squalane, Trehalose và Panthenol cấp ẩm sâu và phục hồi da. Allantoin làm dịu và tái tạo tế bào. Lactic Acid tẩy da chết nhẹ nhàng, làm sáng đều màu da. Chán Tuổi Tinh dầu hạt trà xanh tạo lớp rào cản khóa ẩm, kháng khuẩn và chống oxy hóa. Camtuoi\r\nCông dụng nổi bật: Cấp ẩm sâu, duy trì làn da căng mọng và mịn màng suốt cả ngày. Chống oxy hóa, bảo vệ da khỏi tác hại của môi trường và gốc tự do. Kháng viêm, kháng khuẩn — đặc biệt phù hợp da đang điều trị mụn. Làm dịu da đỏ và kích ứng. Hỗ trợ làm sáng da, mờ thâm và đều màu da theo thời gian. Không gây bít tắc lỗ chân lông (Non-comedogenic tested). Innisfree\r\nKết cấu màu trắng đục hơi đặc nhưng không gây bí da, thấm nhanh sau 2–3 phút, mang lại cảm giác mát dịu dễ chịu. Chán Tuổi Mùi hương trà xanh tự nhiên nhẹ nhàng, thư giãn. Phù hợp mọi loại da, đặc biệt lý tưởng cho da thường đến da khô, da mụn đang điều trị và da nhạy cảm dễ kích ứng.\r\nLưu ý: Sản phẩm có chứa hương liệu, người có da nhạy cảm cao nên patch test trước khi dùng.\r\nCách dùng: Dùng bước cuối trong chu trình dưỡng da sáng và tối. Lấy lượng bằng hạt đậu, massage nhẹ nhàng bằng đầu ngón tay lên khắp mặt và cổ theo chuyển động từ trong ra ngoài cho đến khi thấm hết.	products/figure-1685349791167.png	2
20	Toner Klairs Supple Preparation Unscented	385000	Klairs Supple Preparation Unscented Toner là phiên bản nâng cấp "không mùi" của dòng toner best-seller từ thương hiệu Klairs — thương hiệu skincare lành tính của Hàn Quốc. Được thành lập năm 2010, Klairs luôn hướng đến việc sản xuất các sản phẩm dịu nhẹ, an toàn cho da nhạy cảm, không thử nghiệm trên động vật và không chứa hương liệu hay cồn khô. Vihema Phiên bản Unscented được thiết kế riêng cho những làn da khó chiều, dễ mẩn đỏ và kích ứng với mùi hương.\r\nThành phần nổi bật: Sodium Hyaluronate — dẫn xuất của Hyaluronic Acid với khả năng giữ nước gấp nhiều lần trọng lượng của nó. Vihema Beta-Glucan hỗ trợ làm dịu da, tăng cường sức đề kháng và bảo vệ da khỏi các tác nhân gây hại từ môi trường. tmcco Chiết xuất Centella Asiatica (rau má) phục hồi da tổn thương. Chiết xuất cam thảo làm sáng da và kháng viêm. Phyto-Oligo dưỡng ẩm, ngăn da bị khô. Axit amin lúa mì chống viêm và cấp ẩm sâu. BlogAnChoi Chiết xuất lô hội làm dịu da, dưỡng ẩm sâu và chống oxy hóa. Shopee\r\nCông dụng nổi bật: Cân bằng độ pH da sau bước rửa mặt, giúp các bước skincare tiếp theo thẩm thấu hiệu quả hơn. Cấp ẩm sâu, duy trì làn da mềm mại, căng mướt suốt cả ngày. Làm dịu tức thì da đỏ, da kích ứng và da đang hồi phục. Giảm tình trạng mẩn đỏ và mụn viêm. Tăng cường hàng rào bảo vệ da tự nhiên. Hoàn toàn không gây nhờn rít hay khó chịu.\r\nKết cấu dạng lỏng nhẹ, thẩm thấu nhanh mà không gây nhờn rít. Khi thoa lên da mang lại cảm giác mát dịu, thư giãn tức thì. tmcco Phù hợp mọi loại da — đặc biệt lý tưởng cho da nhạy cảm, da khô, da đang trong quá trình điều trị mụn hoặc phục hồi sau laser.\r\nCách dùng: Sau bước rửa mặt, lấy lượng vừa đủ ra bông tẩy trang hoặc lòng bàn tay, vỗ nhẹ đều khắp mặt. Muốn tăng độ ẩm, có thể áp dụng phương pháp "7 lớp toner" của Hàn — vỗ từng lớp mỏng cho đến khi da căng mọng. Có thể thấm vào bông mặt nạ đắp lên da 10–15 phút như một bước dưỡng ẩm chuyên sâu.	products/nuoc-hoa-hong-khong-mui-klairs.jpg	9
25	Kem Dưỡng Sulwhasoo Concentrated Ginseng Renewing Cream	2850000	Sulwhasoo Concentrated Ginseng Renewing Cream là dòng kem dưỡng chống lão hóa đỉnh cao của thương hiệu Sulwhasoo — biểu tượng K-Beauty luxury trực thuộc tập đoàn AmorePacific, Hàn Quốc. Lấy cảm hứng từ bí quyết dưỡng nhan của các quý phi hoàng thất phương Đông, sản phẩm kết hợp tinh hoa y học cổ truyền với công nghệ sinh học hiện đại.\r\nTrái tim của sản phẩm là GINSENOMICS™ — công nghệ độc quyền chiết xuất saponin từ nhân sâm Hàn Quốc và cô đặc hơn 6.000 lần, nghĩa là cần tới 1.000g nhân sâm mới thu được 1g tinh chất quý giá này. Bên cạnh đó, Hợp chất K từ rễ sâm và Ginsenoside Re từ hoa sâm cùng phối hợp để tái tạo da từ tầng sâu nhất.\r\nCông dụng nổi bật: Tăng độ săn chắc và đàn hồi, đẩy lùi nếp nhăn hiệu quả. Tái tạo và phục hồi tế bào da từ bên trong. Cấp ẩm sâu, duy trì làn da mềm mại và căng mướt suốt cả ngày. Làm sáng da, đều màu nhờ thành phần saponin tự nhiên. Bảo vệ da trước tác nhân oxy hóa và môi trường. Thu nhỏ lỗ chân lông, cải thiện kết cấu da.\r\nKết cấu kem mỏng nhẹ, thấm nhanh, để lại lớp dưỡng mịn lụa trên da cùng hương thơm tinh tế, sang trọng từ rễ và hoa nhân sâm. Phù hợp cho da thường đến da khô, đặc biệt lý tưởng cho làn da có dấu hiệu lão hóa cần được hồi phục và trẻ hóa.\r\nCách dùng: Sau bước dưỡng nước và serum, lấy một lượng vừa đủ, tán đều lên mặt và cổ theo chuyển động từ trong ra ngoài. Dùng sáng và tối.	products/kem-duong-sulwhasoo-concentrated-ginseng-renewing-cream-ex-w_2-e1681454528531.webp	2
26	Serum SK-II Facial Treatment Essence	3200000	SK-II Facial Treatment Essence — hay còn gọi là "Nước Thần" — là sản phẩm chăm sóc da biểu tượng của thương hiệu Nhật Bản SK-II, được hàng triệu phụ nữ trên toàn thế giới tin dùng suốt hơn 40 năm qua.\r\nBí quyết tạo nên sức mạnh của Nước Thần chính là PITERA™ — thành phần độc quyền được phát hiện từ đôi bàn tay mềm mại, trẻ trung bất ngờ của các nghệ nhân làm rượu sake lớn tuổi tại Nhật Bản. Mỗi chai chứa hơn 90% PITERA™ với hơn 50 vi chất sinh học tự nhiên gồm amino acids, vitamin B, C, E, peptides, axit hữu cơ và khoáng chất vi lượng.\r\nCông dụng nổi bật: Làm sáng da, đều màu, mờ đốm nắng và thâm nám. Cấp ẩm sâu, cải thiện da khô căng. Giảm lỗ chân lông, làm mịn kết cấu da. Kích thích tái tạo tế bào, tăng hyaluronic acid tự nhiên. Giảm nếp nhăn, tăng độ đàn hồi và săn chắc.\r\nPhù hợp với mọi loại da: khô, dầu, hỗn hợp và da nhạy cảm. Đặc biệt lý tưởng cho da xỉn màu, thiếu sức sống do stress và thiếu ngủ.\r\nCách dùng: Sau bước rửa mặt và toner, thấm Nước Thần vào bông cotton hoặc lòng bàn tay, vỗ nhẹ khắp mặt và cổ. Dùng sáng và tối để đạt hiệu quả tối ưu.	products/sk-ii-facial-treatment-essence-hydrating-serum-75ml.webp	9
27	Son Môi Đỏ	150000	Son môi đỏ cherry	products/69f7342c-9cea-45ab-a107-c7d616c34ba8_iBpbfoA.webp	1
28	Kem Dưỡng Ẩm	200000	Kem dưỡng ẩm cho da	products/dd_gel_b2879746c8d84a22856364fe9f6cbf1a_1024x1024_d012fe69b2ef4492b80518b6023b2_yKmZtUC.jpg	2
\.


--
-- Data for Name: shop_productimage; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.shop_productimage (id, image, "order", alt, product_id) FROM stdin;
1	products/gallery/5bba142e-30f0-4844-8006-920210412e13_8c8ff1b6867c45419040bf0a7b07d337_grande.png	0	Kem Dưỡng Sulwhasoo Concentrated Ginseng Renewing Cream	25
2	products/gallery/kem-duong-nhan-sam-sulwhasoo-concentrated-ginseng-renewing-cream-2_e8fc_jqcx0di.png	1	Kem Dưỡng Sulwhasoo Concentrated Ginseng Renewing Cream	25
5	products/gallery/3ce-mood-recipe-face-blusher-1.webp	0	Phấn Má Hồng 3CE Mood Recipe Face Blush	24
6	products/gallery/4_8d747c3a2b374dfd848fc9b2d82e4365_1024x1024.png	1	Phấn Má Hồng 3CE Mood Recipe Face Blush	24
7	products/gallery/024d70a2-9ebd-426e-9986-30cacc5198e6-.png	0	Mascara Maybelline Lash Sensational	23
8	products/gallery/315633396_851191289648592_8990646137694611307_n.jpg	1	Mascara Maybelline Lash Sensational	23
13	products/gallery/ftemini_lv1E3Wn.jpg	1	Serum SK-II Facial Treatment Essence	26
14	products/gallery/fte-1_eGkIE0D.webp	1	Serum SK-II Facial Treatment Essence	26
15	products/gallery/figure-1685349791167.png	0	Kem Dưỡng Ẩm	28
16	products/gallery/454g_99d69b6b22114c3d86b4b05238d2b6c6_1024x1024.jpg	1	Kem Dưỡng Ẩm	28
17	products/gallery/69f7342c-9cea-45ab-a107-c7d616c34ba8.webp	0	Son Môi Đỏ	27
18	products/gallery/son-duong-loreal-colour-riche-i-pink-you-cute-chinh-hang-made-in-u_DqSsgCu.com_.jpg	1	Son Môi Đỏ	27
\.


--
-- Data for Name: shop_shipper; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.shop_shipper (id, name, phone, email, vehicle, avatar, status, area, joined_at, note) FROM stdin;
1	Nguyễn Văn Tùng	0923234445	shiper1@gmail.com	Xe máy Wave a		active	Quận 1, Bình Thạnh	2026-04-19	
3	Lê Văn Luyện	0911888999	shiper2@gmail.com	Xe máy Air Blade		active	Quận 3, Quận 5	2026-04-19	
\.


--
-- Data for Name: shop_store; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.shop_store (id, name, address, phone, latitude, longitude) FROM stdin;
2	Store Chanel VIP 1	Nhơn Đức, Nhà Bè, Thành phố Hồ Chí Minh, Việt Nam	0924724824	10.67811	106.9233
3	Shop chanel 3	201 Lê Văn Sỹ, Phường 13, Nhiêu Lộc, Hồ Chí Minh, Việt Nam	0839836341	10.78614	106.68056
1	Chanel shop cơ sở Lê Văn Sĩ	236 Lê Văn Sỹ, Phường 1, Tân Bình, Thành Phố Hồ Chí Minh	0924724824	10.79644	106.66684
4	Nước hoa Chanel 4	23 Lê Văn Sĩ, Phường 1, Tân Bình, Thành Phố Hồ Chí Minh	0924724824	10.771549	106.702695
\.


--
-- Data for Name: shop_storeproduct; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.shop_storeproduct (id, stock, product_id, store_id) FROM stdin;
1	4	22	1
2	5	6	1
3	7	8	1
4	3	9	1
5	2	10	1
6	6	28	1
7	10	14	1
8	6	15	1
9	12	16	1
10	21	25	1
11	9	23	1
12	7	19	1
13	4	17	1
14	12	18	1
15	9	1	1
16	7	21	1
17	4	24	1
18	5	13	1
19	6	12	1
20	7	26	1
21	8	11	1
22	9	3	1
23	3	4	1
24	12	2	1
25	11	27	1
26	13	5	1
27	14	7	1
28	5	20	1
29	11	22	4
30	22	6	4
31	12	8	4
32	14	9	4
33	14	10	4
34	14	28	4
35	12	14	4
36	15	15	4
37	16	16	4
38	17	25	4
39	11	23	4
40	13	19	4
41	8	17	4
42	22	18	4
43	12	1	4
44	2	21	4
45	23	24	4
46	24	13	4
47	11	12	4
48	22	26	4
49	5	11	4
50	4	3	4
51	9	4	4
52	8	2	4
53	7	27	4
54	6	5	4
55	5	7	4
56	4	20	4
57	12	22	3
58	23	6	3
59	32	8	3
60	22	9	3
61	12	10	3
62	42	28	3
63	35	14	3
64	12	15	3
65	56	16	3
66	24	25	3
67	214	23	3
68	0	19	3
69	21	17	3
70	24	18	3
71	24	1	3
72	0	21	3
73	0	24	3
74	0	13	3
75	0	12	3
76	0	26	3
77	0	11	3
78	0	3	3
79	0	4	3
80	0	2	3
81	0	27	3
82	0	5	3
83	0	7	3
84	0	20	3
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 68, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 2, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 33, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 17, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 27, true);


--
-- Name: shop_aboutgallery_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.shop_aboutgallery_id_seq', 1, false);


--
-- Name: shop_aboutpage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.shop_aboutpage_id_seq', 1, true);


--
-- Name: shop_aboutvalue_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.shop_aboutvalue_id_seq', 1, false);


--
-- Name: shop_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.shop_category_id_seq', 10, true);


--
-- Name: shop_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.shop_order_id_seq', 13, true);


--
-- Name: shop_orderitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.shop_orderitem_id_seq', 16, true);


--
-- Name: shop_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.shop_product_id_seq', 28, true);


--
-- Name: shop_productimage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.shop_productimage_id_seq', 18, true);


--
-- Name: shop_shipper_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.shop_shipper_id_seq', 3, true);


--
-- Name: shop_store_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.shop_store_id_seq', 4, true);


--
-- Name: shop_storeproduct_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.shop_storeproduct_id_seq', 84, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: shop_aboutgallery shop_aboutgallery_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_aboutgallery
    ADD CONSTRAINT shop_aboutgallery_pkey PRIMARY KEY (id);


--
-- Name: shop_aboutpage shop_aboutpage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_aboutpage
    ADD CONSTRAINT shop_aboutpage_pkey PRIMARY KEY (id);


--
-- Name: shop_aboutvalue shop_aboutvalue_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_aboutvalue
    ADD CONSTRAINT shop_aboutvalue_pkey PRIMARY KEY (id);


--
-- Name: shop_category shop_category_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_category
    ADD CONSTRAINT shop_category_name_key UNIQUE (name);


--
-- Name: shop_category shop_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_category
    ADD CONSTRAINT shop_category_pkey PRIMARY KEY (id);


--
-- Name: shop_category shop_category_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_category
    ADD CONSTRAINT shop_category_slug_key UNIQUE (slug);


--
-- Name: shop_order shop_order_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_order
    ADD CONSTRAINT shop_order_pkey PRIMARY KEY (id);


--
-- Name: shop_orderitem shop_orderitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_orderitem
    ADD CONSTRAINT shop_orderitem_pkey PRIMARY KEY (id);


--
-- Name: shop_product shop_product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_product
    ADD CONSTRAINT shop_product_pkey PRIMARY KEY (id);


--
-- Name: shop_productimage shop_productimage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_productimage
    ADD CONSTRAINT shop_productimage_pkey PRIMARY KEY (id);


--
-- Name: shop_shipper shop_shipper_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_shipper
    ADD CONSTRAINT shop_shipper_pkey PRIMARY KEY (id);


--
-- Name: shop_store shop_store_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_store
    ADD CONSTRAINT shop_store_pkey PRIMARY KEY (id);


--
-- Name: shop_storeproduct shop_storeproduct_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_storeproduct
    ADD CONSTRAINT shop_storeproduct_pkey PRIMARY KEY (id);


--
-- Name: shop_storeproduct shop_storeproduct_store_id_product_id_f1a1171e_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_storeproduct
    ADD CONSTRAINT shop_storeproduct_store_id_product_id_f1a1171e_uniq UNIQUE (store_id, product_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: shop_aboutgallery_about_id_9b96a5fa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX shop_aboutgallery_about_id_9b96a5fa ON public.shop_aboutgallery USING btree (about_id);


--
-- Name: shop_aboutvalue_about_id_7029e3e6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX shop_aboutvalue_about_id_7029e3e6 ON public.shop_aboutvalue USING btree (about_id);


--
-- Name: shop_category_name_11b68823_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX shop_category_name_11b68823_like ON public.shop_category USING btree (name varchar_pattern_ops);


--
-- Name: shop_category_slug_4508178e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX shop_category_slug_4508178e_like ON public.shop_category USING btree (slug varchar_pattern_ops);


--
-- Name: shop_order_shipper_id_bdcb77bf; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX shop_order_shipper_id_bdcb77bf ON public.shop_order USING btree (shipper_id);


--
-- Name: shop_order_store_id_b64955cb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX shop_order_store_id_b64955cb ON public.shop_order USING btree (store_id);


--
-- Name: shop_order_user_id_00aba627; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX shop_order_user_id_00aba627 ON public.shop_order USING btree (user_id);


--
-- Name: shop_orderitem_order_id_2f1b00cf; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX shop_orderitem_order_id_2f1b00cf ON public.shop_orderitem USING btree (order_id);


--
-- Name: shop_orderitem_product_id_48153f22; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX shop_orderitem_product_id_48153f22 ON public.shop_orderitem USING btree (product_id);


--
-- Name: shop_product_category_id_14d7eea8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX shop_product_category_id_14d7eea8 ON public.shop_product USING btree (category_id);


--
-- Name: shop_productimage_product_id_65b3b20c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX shop_productimage_product_id_65b3b20c ON public.shop_productimage USING btree (product_id);


--
-- Name: shop_storeproduct_product_id_1dc37396; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX shop_storeproduct_product_id_1dc37396 ON public.shop_storeproduct USING btree (product_id);


--
-- Name: shop_storeproduct_store_id_0e27c000; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX shop_storeproduct_store_id_0e27c000 ON public.shop_storeproduct USING btree (store_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shop_aboutgallery shop_aboutgallery_about_id_9b96a5fa_fk_shop_aboutpage_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_aboutgallery
    ADD CONSTRAINT shop_aboutgallery_about_id_9b96a5fa_fk_shop_aboutpage_id FOREIGN KEY (about_id) REFERENCES public.shop_aboutpage(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shop_aboutvalue shop_aboutvalue_about_id_7029e3e6_fk_shop_aboutpage_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_aboutvalue
    ADD CONSTRAINT shop_aboutvalue_about_id_7029e3e6_fk_shop_aboutpage_id FOREIGN KEY (about_id) REFERENCES public.shop_aboutpage(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shop_order shop_order_shipper_id_bdcb77bf_fk_shop_shipper_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_order
    ADD CONSTRAINT shop_order_shipper_id_bdcb77bf_fk_shop_shipper_id FOREIGN KEY (shipper_id) REFERENCES public.shop_shipper(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shop_order shop_order_store_id_b64955cb_fk_shop_store_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_order
    ADD CONSTRAINT shop_order_store_id_b64955cb_fk_shop_store_id FOREIGN KEY (store_id) REFERENCES public.shop_store(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shop_order shop_order_user_id_00aba627_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_order
    ADD CONSTRAINT shop_order_user_id_00aba627_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shop_orderitem shop_orderitem_order_id_2f1b00cf_fk_shop_order_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_orderitem
    ADD CONSTRAINT shop_orderitem_order_id_2f1b00cf_fk_shop_order_id FOREIGN KEY (order_id) REFERENCES public.shop_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shop_orderitem shop_orderitem_product_id_48153f22_fk_shop_product_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_orderitem
    ADD CONSTRAINT shop_orderitem_product_id_48153f22_fk_shop_product_id FOREIGN KEY (product_id) REFERENCES public.shop_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shop_product shop_product_category_id_14d7eea8_fk_shop_category_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_product
    ADD CONSTRAINT shop_product_category_id_14d7eea8_fk_shop_category_id FOREIGN KEY (category_id) REFERENCES public.shop_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shop_productimage shop_productimage_product_id_65b3b20c_fk_shop_product_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_productimage
    ADD CONSTRAINT shop_productimage_product_id_65b3b20c_fk_shop_product_id FOREIGN KEY (product_id) REFERENCES public.shop_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shop_storeproduct shop_storeproduct_product_id_1dc37396_fk_shop_product_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_storeproduct
    ADD CONSTRAINT shop_storeproduct_product_id_1dc37396_fk_shop_product_id FOREIGN KEY (product_id) REFERENCES public.shop_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shop_storeproduct shop_storeproduct_store_id_0e27c000_fk_shop_store_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_storeproduct
    ADD CONSTRAINT shop_storeproduct_store_id_0e27c000_fk_shop_store_id FOREIGN KEY (store_id) REFERENCES public.shop_store(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

